# Generated by Django 5.1.4 on 2025-01-28 21:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buzzer_web', '0002_team_color_team_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='BuzzerLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('action', models.CharField(choices=[('buzz', 'Buzz'), ('reset', 'Reset')], max_length=50)),
                ('color', models.CharField(default='#000000', max_length=50)),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='buzzer_web.team')),
            ],
        ),
    ]
