# Generated by Django 5.1.3 on 2025-03-09 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buzzer_web', '0003_buzzerlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allow_self_reset', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Game Settings',
            },
        ),
    ]
